### ISSUE TITLE
Betting: Potential incorrect earning calculation

### ISSUE THREAD

**Issue by madhav-halbe** [sidebetz/feedback#14]
**Environment**
- [ ] https://dev/sidebetz.ai

**UserDetails / Login details**
- [ ] OAuth

Email: madhav@sidebetz.ai

**Describe the bug**
Please take a look at the earnings for hand # 12, shouldn't it be +608?

<img width="1468" alt="Screenshot 2024-08-06 at 2 52 14 PM" src="https://github.com/user-attachments/assets/f18ed923-e2dc-42c6-9188-fc05b1c970f7">

**Comment by mrnthv** [comment]
@madhav-halbe @duck-tape The calculations on the right side are correct
For win cases in hand numbers 12 and 6 we have
(100/7210)*600 = 8.3 ~ 8
(238/100)*200 = 476

For loss cases, the entire amount bet is shown as negative earning.

Let me know if you wanted to indicate if win/loss player identification itself is wrong.

**Comment by mrnthv** [comment]
@

> **Environment**
> 
> * [ ]  https://dev/sidebetz.ai
> 
> **UserDetails / Login details**
> 
> * [ ]  OAuth
> 
> Email: [madhav@sidebetz.ai](mailto:madhav@sidebetz.ai)
> 
> **Describe the bug** Please take a look at the earnings for hand # 12, shouldn't it be +608?
> 
> <img alt="Screenshot 2024-08-06 at 2 52 14 PM" width="1468" src="https://private-user-images.githubusercontent.com/177058634/355612921-f18ed923-e2dc-42c6-9188-fc05b1c970f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg2MTcsIm5iZiI6MTcyMzAzODMxNywicGF0aCI6Ii8xNzcwNTg2MzQvMzU1NjEyOTIxLWYxOGVkOTIzLWUyZGMtNDJjNi05MTg4LWZjMDViMWM5NzBmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxMzQ1MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjdlM2FmNTg2YzgxODY2NDJiODcwZjNhNGIxNDIzODJiMTJjMmQyYjE1YmUxNGNjZDI2YmEwZjdiMDYzYTZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.I6VlK07AnL4Mx6Q1wm_Of1-ndf9nYm-o3zuYW9JtHzU">

@madhav-halbe 
We are reporting the differential earnings for both win as well as loss cases.
If a sidebettor has bet 600 and wins back 608 the net earning is 8.
And if a sidebettor has bet 200 on a losing player, the net earning would be -200
Seems logical. For hand 12 earning of 608 would be at odds of ~ 100. Odds in this case were -7210. So earning of 8 aptly indicates a very low earning on a very low odds.

Actually one reason for doing this was to reconcile the tournament balance using the formula (Initial balance + All positive earnings - All negative earnings). Using the above approach the calculations were reconciling.
But if we used 608 instead of 8, it would not reconcile with regular calculation. So a sidebettor will have hard time confirming that their tournament balance is correctly displayed wrt earnings.

In above screenshot tournament balance 9784 = (10000 +8-200-200-300+476)

**Comment by madhav-halbe** [comment]
@mrnthv Got it! My bad!

**Comment by duck-tape** [comment]
@madhav-halbe  closing issue since this is correct behavior. If you observe anything else odd please open a new issue with details
